- webapp/lib/model.g.dart
- webapp/lib/model.yaml
This adds a new MessageStatus enum field in each message to track messages that are sent from the nook client through rapid_pro. 
* `pending` - message was sent to rapid_pro but send has not yet been confirmed
* `confirmed` - confirmation received from rapid_pro that message was sent
* `failed` - message send failed somewhere in the process
* `unknown` - catch all for non-of-the-above until all messages have a status
> add Message.status enum to track progress through rapidpro

- webapp/lib/controller.dart
This hooks the `SystemMessage` model objects to the banner so that admin-level messages will appear in all clients.
Feel free to land this if the review looks good.
> display system messages

- webapp/lib/model.g.dart
- webapp/lib/platform.dart
As another step towards [removing firebase from the model](https://github.com/larksystems/Project-2019-WorldBank-PLR/issues/31), this PR replaces `firestore.WriteBatch` with `DocUpdate`.
> replace firestore.WriteBatch with DocUpdate

- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/platform.dart
Currently, the nook model is tightly coupled to firebase, which prevents local testing and driving the model using json or other storage solutions. This PR is the first step in refactoring the model so that firebase is not directly used by the model.
See https://github.com/larksystems/Project-2019-WorldBank-PLR/issues/31
> Refactor model use of firebase

- webapp/lib/model.g.dart
Another step in [refactor model use of firebase](https://github.com/larksystems/Project-2019-WorldBank-PLR/issues/31), this PR wraps `Firestore.collection(collectionRoot).onSnapshot` in a call to `DocStorage.onChange`.
> Wrap Firestore.collection(collectionRoot).onSnapshot

- webapp/lib/model.g.dart
- webapp/lib/platform.dart
This renames 3 model classes
* `DocUpdateBatch` to `DocBatchUpdate`
* `FirestoreDocUpdateBatch` to `FirebaseBatchUpdate`
* `FirestoreDocStorage` to `FirebaseDocStorage`
> rename some model classes

- webapp/lib/model.g.dart
- webapp/lib/platform.dart
Another step in [refactor model use of firebase](https://github.com/larksystems/Project-2019-WorldBank-PLR/issues/31), this PR updates the various listen and update methods to use DocStorage rather than Firebase.
> refactor listen/update to use DocStorage

- webapp/web/messages.css
- webapp/web/reset.css
- webapp/web/styles.css
Beforehand the size of all panels was done only through flex-box, which made it dependent on the content. This turns out to behave badly when, e.g. there are text messages without spaces on which the line should break.
Fixes #161
> Set main panel widths relative to window width

- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model_firebase.dart
- webapp/lib/platform.dart
This PR finishes moving Firebase specific functionality out of both `model.dart` and `model.g.dart` and into a new `model_firebase.dart` file. This is a step closer to driving nook tests with json rather than firebase.
Fix https://github.com/larksystems/KK-Project-2019-WorldBank-PLR/issues/31
> move firebase specific functionality out of model

- .github/workflows/README.md
- .github/workflows/mariana.yml
A proposal GitHub workflow for automating the generation of project cards when assigning issues, opening PRs and requesting PR reviews.
I'm not super happy with the solution, but it also seems that this is the best that is available at the moment. Perhaps in the future GitHub will also add automation to adding cards to projects, not just inside projects. In the meantime, please have a look at the code, and here are some of my concerns:
Since there doesn't seem to be a syntax for loops in GitHub workflows, we'll need to list each project/user separately - I was thinking each of us could have our own file.
Another potential downside is that these workflows run per repo, so we would need to import them into each (old and new) repo. I'm not entirely sure whether it's worth littering the …
> Add sample workflow file for automating issues and PRs

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
- webapp/web/styles.css
This PR adds a new "after date" filter to show only conversations whose last message has a timestamp more recent than a specified date/time.
When selected, a new text area appears in which a date / time can be entered. The format is YYYY MM DD HH. The year is required and must be a contiguous group of 4 digits at the start, but the month, day, and hour are optional and all non-numeric characters entered in this text field will be ignored when parsing the date/time.
When the "Apply" button is clicked or the "Enter" key is pressed, the text is parsed into a date/time and applied as a filter
> new "after date" conversation filter

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
- webapp/web/styles.css
Re #189
This is a first step for having two filter lists - one for tags to search for, another for tags to exclude, plus an AND/OR operator on each list.
Currently the exclude list is empty and not functional, that's coming up next.
cc @lukechurch for feedback on the UI approach
Screenshots:
> Add initial separation between include and exclude filters

- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
- webapp/lib/pubsub.dart
This changes the underlying model so that changes to the `Conversation` `unread` flag in firebase are made via pub/sub rather than directly updating firebase.
* `setUnread` - update the `unread` flag for a single conversation
* `setAllUnread` - update the `unread` flag for multiple conversations
A new `DocPubSubUpdate` class (interface) has been added so that the model does not have to know the specifics behind pub/sub implementation.
For background see [reroute nook actions through pub/sub](https://github.com/larksystems/KK-Project-2020-IOM/issues/18)
> Update unread flag via pub/sub

- webapp/lib/controller.dart
When [Conversation.notes are updated via pub/sub](https://github.com/larksystems/nook/pull/197), the updates will no longer be going directly to firebase, and the exception handling code specific to firebase can be removed.
> cleanup save note action

- webapp/lib/view.dart
This update the "notes" field so that keystrokes do not trigger other actions such as tagging a conversation or sending a message.
> fix note keystrokes triggering other actions

- webapp/lib/controller.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
This builds on the prior [refactor save text action PR](https://github.com/larksystems/nook/pull/202) so that reply.translation changes are consolidated over a rolling 3 second period and updated via pub/sub rather than directly modifying firebase.
In addition, 2 unused `Message` methods were removed.
cc @lukechurch
> redirect reply.translation to be updated via pub/sub 

- webapp/pubspec.yaml
I'm using extension methods in an upcoming PR - if you don't think it's a good idea to go to Dart 2.7, please let me know and I'm happy to go back.
Thanks!
> Bump dart SDK version so we can use extension methods

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
- webapp/pubspec.yaml
- webapp/web/styles.css
Continuing work on more expressive filtering #189 
At the moment, only the tags are considered for the OR/AND operation, the after date is always an AND, even though it's not differentiated in the UI as such. Based on the use cases discussed so far, I think it makes sense to show that its effect is different - @lukechurch can you confirm that this makes sense?
Thanks (and sorry for the slightly extensive change)!
Mini demo:
there are 2 conversations, tagged as follows:
conv1 - tag1
conv2 - tag2
show *any* tag1 tag2:
show *all* tag1 tag2:
hide *all* tag1:
> Separate between include and exclude filters

- webapp/lib/controller.dart
- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
This reroutes changes to `Conversation.tagIds` through pub/sub [rather than modifying firebase directly](https://github.com/larksystems/KK-Project-2020-IOM/issues/18). In addition:
* `Conversation.tagIds` is now a `Set` rather than a `List`
* added `docId` to `SuggestedReply` and `SystemMessage`
Next steps include
* introduce new add/remove pub/sub actions in `pubsub_handler.py`
* rework `addConversationTag` and `removeConversationTag` functions to use the new add/remove pub/sub actions
> reroute conversation tag updates through pub/sub

- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/platform.dart
- webapp/lib/pubsub.dart
This updates `Conversation.tagIds` to use the new pub/sub based add to and remove from list operations. In addition `setAll<fieldName>` is renamed to `set<fieldName>_forAll`
See [reroute nook actions through pub/sub](https://github.com/larksystems/KK-Project-2020-IOM/issues/18)
> update Conversation.tagIds to use pub/sub add/remove

- webapp/lib/controller_view_helper.dart
Fixes #159 
I think in the future we'll want to have an indicator in the conversation list as to who sent the last message (ie. us via Nook or the person we're talking to), or we may want to always show the last message of the conversant and never from us, but for now, showing the last message should be an improvement.
cc @lukechurch
> Show last message not first in conversation summary

- webapp/lib/controller.dart
- webapp/lib/view.dart
- webapp/web/styles.css
Re #162 
This creates a top menu for switching between the conversation view (the UI we already have) and the outbox, an upcoming new view for managing outgoing messages (delayed sending to allow double checking, scheduled sending etc.)
As with the filtering feature, because it's a substantial change and intermediate versions might not work, I'm working on a separate branch off master (`dev-outbox`) which when ready, I'll merge into master.
cc @lukechurch for following progress and feedback on UI design
Demo:
> Add support for two views in preparation of adding an outbox feature

- webapp/lib/controller.dart
If I launch nook and I am already signed in (which I typically am) then it immediately displays the conversation view (which I think is correct), but the tags view on the right is empty. If I sign out then back in, the tags appear and all is well.
After digging I found that if the `actionObjecState` is not initialized, then the tags view on the right is empty. This PR adds that initialization so that the tags show up without having to log out then back in again.
> initialize actionObjectState

- webapp/lib/controller.dart
- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
This updates the controller, platform, and model to use pub/sub when
* adding a message tag
* removing a message tag
* updating a message translation
In addition, updating a message translation now uses `SaveTextAction` similar to updating a conversation note.
Fix https://github.com/larksystems/KK-Project-2020-IOM/issues/18
> Update message tags and translation via pub/sub

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
- webapp/lib/view.dart
This simplifies the hand written portion of the model by extension methods. Changes include:
* replace `conversation.deidentifiedPhoneNumber.value`
by `conversation.docId`
* replace `conversation.deidentifiedPhoneNumber.shoftValue`
by  `conversation.shortDeidentifiedPhoneNumber`
* remove `class DeidentifiedPhoneNumber`
* simplify `Conversation` class using extension
> use extension methods

- webapp/lib/controller.dart
- webapp/lib/pubsub.dart
I think the `dart:io` library got introduced accidentally In #217 and I didn't catch it in review either, resulting in the app not compiling any more.
Is there a particular reason why `PubSubException` should inherit from `IOException`, or can it inherit directly from `Exception`? If it's not too important, here's a simple PR to remove the `dart:io` imports and remove `IOException`, but if you would like to do this a different way, happy to discuss.
Thanks!
> Remove reference to dart:io libary from web platform code

- tool/firebase_to_json.py
- tool/json_to_firebase.py
This should help us download and upload e.g. the translation cache independent of the rest of the collections.
The change for `json_to_firebase.py` ended up being primarily adding argparse to manage arguments. I figured we might want to add that later on anyway, but if you'd prefer me to revert it for now, I can happily do that.
Thanks!
> Use argparse and can now refer to single root keys

- webapp/lib/controller.dart
- webapp/lib/platform.dart
Follow on from #217 which changed the return type of the pubsub methods to `Future<void>`, this does the same for the platform methods, otherwise the following error appears whenever a message is sent from the UI:
`Uncaught Error: Type '_Future<void>' should be '_Future<bool>' to implement expected type 'Future<bool>'.`
It seems that the static type checking isn't catching `Future<T>` differences in return type.
> Propagate void return type from pubsub, remove exception handling in controller

- webapp/lib/controller.dart
- webapp/lib/view.dart
- webapp/web/actions.css
We've added a hide age-related tags checkbox in #228 , but it was a bit hacky and would only hide tags in the panel, not also in the tag filter menu.
This PR wires the checkbox to the controller, which can then propagate the hide/show decision in all the right places.
The way we check which tags to hide (ie. age by trying to parse the text) is still a bit hacky and we'll need to have a more sensible solution in the future.
I'm also not super fond of the names I was able to pick - if you have anything better than `_filterAgeTagsIfNeeded` plmk :)
Thanks!
> Replace hacky view-only tag filtering

- webapp/lib/controller.dart
This updates nook to check if the active conversation has changed when new conversation data arrives. If it has changed, then the active conversation data is replaced with new conversation data and the conversation view is updated.
Feel free to merge this PR if it is helpful.
> update active conversation when new data arrives

- webapp/lib/lazy_list_view_model.dart
This improves the scrolling in the lazily loaded conversations list by adding a single `_scrollPad` DOM element representing the not-yet-loaded DOM elements. The size of this DOM element is dynamically updated as new elements are loaded resulting in a scroll bar that closely approximates behavior if all of the elements were loaded. It also results in a small non-item white area at the end of the list so that you now can tell that you have indeed scrolled to the end and there are no more items.
Hopefully this will improve https://github.com/larksystems/nook/issues/256
Feel free to merge this PR if it proves helpful.
> improve scrolling in conversation list

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
This modifies firebase update processing so that conversation summaries in the conversation list are updated in place rather than recomputing the entire list each time a new conversation update arrives.
Hopefully addresses https://github.com/larksystems/nook/issues/257
Feel free to squash/merge this if it is helpful.
> update conversation list in place when processing updates from firebase

- webapp/lib/lazy_list_view_model.dart
- webapp/lib/view.dart
Removing an item from DOM only resulted in the item not getting added back to the DOM if it needed to get back into the list. This now syncs the DOM list with the lazy list by removing the element from the DOM via the lazy list.
@danrubel In particular, does the update of the scrollPad in `removeItem` make sense? Should I be doing anything else when removing an item from the list?
Thanks!
> Remove item from DOM via removal from lazy list

- webapp/lib/controller_view_helper.dart
- webapp/lib/lazy_list_view_model.dart
- webapp/lib/view.dart
I failed to reproduce https://github.com/larksystems/nook/issues/279, but on reading the code it appears that a conversations would not be removed from the list. I think this is what's needed but not confident because I could not repo the problem or don't understand how to properly do so.
Feel free to merge this, use as part of some other PR, or toss this as you see fit.
> remove updated conversation from list if filter does not match

- webapp/lib/view.dart
I think it would be a good idea to hide the conversation list selector until it's fully functional as it might confuse people trying to use it. I've added TODOs to the code to keep track of it.
cc @lukechurch 
Thanks!
> Hide conversation list selector until fully implemented

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
- webapp/lib/view.dart
- webapp/web/styles.css
This PR loads shards from `/nook_conversation_shards` and populates the conversation list selection dropdown with what is found. Another step towards https://github.com/larksystems/nook/issues/263
* When the user selects a list, then the conversation list is populated  from `/nook_conversation_shards/<shard-doc-id>/conversations`
* If exactly one shard is found, then the conversation list dropdown is not shown
and the conversations are loaded from that one shard
* If no shards are found, then the conversation list dropdown is not shown 
and conversations are loaded from `nook_conversations`
Here are some screenshot of what the user sees if more than one shard found...
-----------------------
-----------------------
> populate list of conversation lists

- webapp/lib/view.dart
Sorry - when I merged master into a previous PR using GitHub's web merge conflict tool, I accidentally missed adding a closing brace to a method, resulting in nook no longer building. This fixes it.
Merging immediately to avoid master being unable to build for long.
TBR @danrubel
> Close braces for method which caused build failure

- webapp/lib/controller.dart
- webapp/lib/view.dart
With this PR, if the name of a conversation list is changed in firebase (e.g. `Conversation list #1` changes to `Brian's conversations`), then the UI automatically reflects that change. In addition there is a fix to clear the list of conversations cached in the browser when a different conversation list is selected.
> dynamically update conversation list names

- webapp/lib/controller.dart
- webapp/lib/model.g.dart
- webapp/lib/model_firebase.dart
This propagates doc removals from firebase into the UI.
At the moment it's not working well for conversations (which get removed from the internal model but not from the UI) and conversations shards. Will follow up with separate PRs to fix conversations and conversation shards.
> Separate firebase doc changes into added/modified/removed

- webapp/lib/controller.dart
- webapp/lib/model.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
- webapp/lib/view.dart
- webapp/web/index.html
- webapp/web/styles.css
- webapp/web/utilities.css
Closes #286 
Follows up from #291 by replacing the single read of user configuration from firebase into a listener for any changes, and adding in the ability to hide/show the tag panel.
Thanks!
> Listen to user configuration of UI features changes from firebase

- webapp/lib/lazy_list_view_model.dart
- webapp/lib/view.dart
This reduces load time delays due to DOM render and reflow from about 7s to 250ms on my machine for 2k conversations.
> Add conversations to the list in one go rather than one by one

- tool/compute_tag_analytics.py
The current data setup for theme analytics reporting is different to those for nook_watcher and would likely require some firebase datastore layout changes. Best to just remove it for now to allow the rest of the analytics to run.
> Remove logging the project for the theme analytics

- tool/compute_tag_analytics.py
The previous code was assuming that message timestamps were timezone aware, but it seems that that may not always be the case. It now considers them as being in UTC if they don't have a timezone.
> Consider unaware timestamps as UTC

- .gitignore
- tool/deploy_webapp_with_metadata.sh
This merges 
* `deployment/deploy.sh`
* `deploy_webapp.sh`
into a new `deploy_webapp_with_metadata.sh` script that deploys nook
and updates firebase with information about the deployment
```
/metadata/nook_app
deployed_by:      "user-git-email-address"
latestCommitHash: "fafb00e3ed67b23d72041e937fbd7c5b1d73e17b"
timestamp:        "2020-04-01T22:02:48"
```
> deploy webapp with metadata

- webapp/lib/controller.dart
- webapp/lib/view.dart
With this PR, the conversation list checkboxes will be shown all the time if the `send_multi_message_enabled` flag is set to `true`, as opposed to only when the select all checkbox is ticked. This is to support selecting messages one by one, starting from no selected messages.
> Update checkboxes logic

- webapp/lib/controller.dart
If a conversation is removed from firebase, or no longer meets the filter, it will now be removed from the list. If in the meantime it gets added again to the list, it will appear at the end.
[It unfortunately introduces a slight inconsistency - in the internal list tracking the conversations ( ie. `filteredConversations`), the removed-and-then-added-again conversation will be in its old position, so if navigating to it via any other way other than clicking on it, the conversation selection will jump as if the conversation was in the old place rather than at the end. In the long term this will need fixing, but hopefully it's a rare occurrence that it doesn't need a fix today.]
> Handle conversation removal from the list

- webapp/lib/controller.dart
- webapp/lib/view.dart
This fixes an issue when, if multiple conversations were selected and the `send_multi_message_enabled` was set to false afterwards, the multiple messages were still selected in the background, resulting in multiple messages still being sent.
Also changes `applyConfiguration` to update only the features for which the configuration has changed.
> Apply configs only on change and reset checkboxes when changing the config

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/logger.dart
- webapp/lib/platform.dart
- webapp/lib/platform_constants.dart
- webapp/lib/pubsub.dart
- webapp/lib/view.dart
This also adds a snackbar/toast that could be triggered from the platform. I initially did this so I can trigger the snackbar to show failures, but since it's so intrusive, I ended up using the banner notification instead.
> Add uptime monitoring every min and every 5 secs if minute ping fails

- functions/package-lock.json
- functions/package.json
This should also fix the security issues reported by Github with `acorn` and `minimist`, which are indirect dependencies for us.
> Update node packages

- tool/deploy_webapp.sh
This introduces an upfront check between the firebase constants file and the crypto token to ensure that they both point to the same project.
It also fixes an issue where the script args needed to be passed either as absolute paths, or needed to be under the project repo root (because of the `cd "$(dirname "$0")"/..` command).
> Compare project ids & fix relative path issue

- tool/deploy_webapp.sh
Missed this when testing the previous change - which caused the script to fail for relative crypto token paths.
> Add cd to work dir after getting full paths

- tool/deploy_webapp.sh
Fixes #342 - the cause of that issue were the file variables being passed to `cat`, but I've now wrapped all other variables in quotes just in case.
> Wrap variables in quotes

- webapp/lib/controller.dart
- webapp/lib/view.dart
The missing config reads in views were causing the UI to indicate that some functionality was available, when it was actually disabled (e.g. showing the tag panel, shortcuts and custom message box).
The `show(bool value)` was a bit confusing, so switching to separate show/hide methods for clarity.
> Add missing config reads in views & use show/hide API

- webapp/lib/controller.dart
- webapp/lib/view.dart
This PR does two things:
- it disables multi-message send with shortcuts - the user now has to use the explicit send button
- if a modifier key is pressed at the same time as another key, we don't send the matching suggested reply - this is to avoid sending messages when the user wants to use typical keyboard shortcuts in chrome (ctrl-c/ctrl-v/ctrl-0 etc)
> Make it harder to send multi messages with keyboard shortcuts

- webapp/lib/model.dart
This generates `add_opinion` when a translation is changed (see below).
Needs https://github.com/larksystems/Katikati-Core/pull/157 for pup/sub to forward this to piety.
```
{
"datetime": "2020-05-27T01:57:54.340633+00:00",
"src": "nook",
"action": "add_opinion",
"namespace": "nook_messages/set_translation",
"opinion": {
"conversation_id": "nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16",
"message_id": "nook-message-nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16-f7d8a732bebbefa8822f0818bff39acdecd002db0c70f38a06110fbff573513e-10128",
"text": "KAMA GANI",
"translation": "Does this include the original text?",
"_authenticatedUserEmail": "dan@lark.systems",
"_authenticatedUserDisplayName": "Dan Rubel"
}
}
```
> set translation via publish add_opinion

- webapp/lib/view.dart
Please take a look - I think this is behaviourally identical, but improves runtime from 7000ms to 50ms for 7000 items.
> Pre-compute UUID set during updateConversationList

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/view.dart
- webapp/web/styles.css
This PR addresses #349 by:
- adding categories for tags in the same way that we have added for suggested replies
- using the categories in the filtering UI via a category selector
- also setting an upper limit on the height of the tag filtering menu making the list to scroll if there are too many tags, this should make it more usable even when we're not using categories
> Add implementation for filtering hierarchical tags

- webapp/lib/model.g.dart
- webapp/lib/model.yaml
- webapp/lib/platform.dart
This changes nook to communicate conversation tag changes via published `add_opinion`:
Add tags:
```
{
"datetime": "2020-05-27T16:49:24.177521+00:00",
"src": "nook",
"action": "add_opinion",
"namespace": "nook_conversations/add_tags",
"opinion": {
"conversation_id": "nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16",
"tagIds": ["tag-029ddfbc"],
"_authenticatedUserEmail": "dan@lark.systems",
"_authenticatedUserDisplayName": "Dan Rubel"
}
}
```
Remove tags:
```
{
"datetime": "2020-05-27T16:49:30.809827+00:00",
"src": "nook", "action": "add_opinion",
"namespace": "nook_conversations/remove_tags",
"opinion": {
"conversation_id": "nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16",
"tagIds": ["tag-029ddfbc"],
"_authenticatedUserEmail": "dan@lark.systems", …
```
> modify conversation tag via add opinion

- webapp/lib/model.g.dart
- webapp/lib/platform.dart
This changes nook to communicate unread flag changes via published `add_opinion`:
```
{
"datetime": "2020-05-27T18:53:02.452270+00:00",
"src": "nook",
"action": "add_opinion",
"namespace": "nook_conversations/set_unread",
"opinion": {
"conversation_id": "nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16",
"unread": true,
"_authenticatedUserEmail": "dan@lark.systems",
"_authenticatedUserDisplayName": "Dan Rubel"
}
}
```
> set unread via add opinion

- webapp/lib/model.g.dart
This changes nook to communicate notes changes via published `add_opinion`:
```
{
"datetime": "2020-05-27T17:36:35.065945+00:00",
"src": "nook", "action": "add_opinion",
"namespace": "nook_conversations/set_notes",
"opinion": {
"conversation_id": "nook-phone-uuid-46d4a969-5ac7-4845-85de-8eb31c0dad16",
"notes": "Some new notes vis",
"_authenticatedUserEmail": "dan@lark.systems",
"_authenticatedUserDisplayName": "Dan Rubel"
}
}
```
> change setNotes to publish add_opinion

- webapp/lib/model.g.dart
- webapp/lib/pubsub.dart
This removes functionality that supports "publish `update_firebase`"
now that we have switched over entirely to use "publish `add_opinion`"
> remove unused functionality

- webapp/lib/view.dart
- webapp/web/actions.css
- webapp/web/messages.css
- webapp/web/styles.css
- webapp/web/utilities.css
* Fixes #379 which was caused by the not removing the width classes between tag panel visibility changes
* Long tag names without spaces in the tag panel will break on multiple lines if there's not enough space for them in the panel
* "Tag" buttons are also now floating over the text of the tag (as for the suggested replies)
> Various layout fixes

- webapp/lib/controller.dart
- webapp/lib/view.dart
Fixes #383 
By keeping the active conversation on the screen even when it no longer meets filtering constraints, the `activeConversation.docId` may not be in the `view.conversationListPanelView`. This PR addresses this by checking if it is there before trying to select it and adding null checks for markUnread/check operations.
> Fix errors thrown when the active conversation is no longer in the list view

- webapp/lib/controller.dart
The `extractTagIdsWithMissingInfo` function was making the assumption that its `tags` argument contained only tags without missing info which was an artefact of a previous logic.
> Fix issue where missing tags were being removed when switching conversation list

- webapp/web/actions.css
- webapp/web/banner.css
- webapp/web/load_spinner.css
- webapp/web/messages.css
- webapp/web/reset.css
- webapp/web/snackbar.css
- webapp/web/styles.css
- webapp/web/tags.css
- webapp/web/utilities.css
This at-rule is useful for using non-ASCII characters in some CSS properties (e.g. content), which we do for the new filter menu (I caught the browser not interpreting this correctly today for some reason).
> Add @charset utf-8 to css files to specify encoding

- webapp/lib/controller.dart
It turns out the proper fix for #395 is fairly simple - we were only removing them from the view, but not from the internal app state.
> Fix issue where tags were removed from view but not app controller state

- webapp/lib/controller.dart
This was introduced in #404 and was causing Nook not to load for users with the conversational turns feature disabled
TBR
> Fix last turn inbound tags filter list being null instead of empty

- webapp/lib/controller.dart
- webapp/lib/model.dart
I always forget that dart2js compilation strips off asserts... not sure if there's a compilation flag we could pass for it not to do that?
In any case, this replaces the asserts with explicit error that can also be interpreted by the user, and also makes the internal state dependent on whether there was an error thrown or not for tags (beforehand, the tag was added/removed regardless of whether the error was being thrown, and because of the previous check to avoid adding/removing the tag again, it could never be added/removed later on). For translations, the user can trigger another save by editing the translation - I'd rather not delete the text they just wrote. But if you have any thoughts as to a better behaviour, plmk.
Thanks!
> Replace asserts with explicit error throwing

- webapp/lib/model.g.dart
This functionality is not used by nook and will not be part of the updated codegen
> remove unused enum fromStringOverride functionality

- webapp/lib/model.g.dart
This PR contains several enum change based on new codegen, but no functional changes:
* new enum `fromData` and `toData` methods
* update model classes to use new enum `fromData` and `toData` methods rather than `fromString` and `toString`
* syntax style cleanup of enum `fromString` method
Two reasons behind these changes:
1) The `toString` method in Dart is typically used for debugging and it is better to have a distinct `toData` method for converting enums into data. The enum `toString` and `toData` methods happen to return the same thing today but may diverge in the future.
2) Updating codegen to call enum `fromData` makes it more consistent with all other generated model classes.
> split enum to/fromString and to/fromData

- webapp/lib/controller.dart
- webapp/lib/controller_filter_helper.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
- webapp/web/styles.css
This is a big and messy change, sorry in advance...
Basically it brings back the exclude filter prototyped a while back ( #194 and #208). With quite a bit of the code needing to be shared between the (now) three filters, I took the earlier approach of grouping the filters in a class and differentiating between them via a `TagFilterType` enum (hence some of the more recent last inbound turn code being deleted).
The CSS changes are to make the management of the stacked filter menus better, by changing the hover border from a rectangle taking the whole left side of the menu to a triangle:
Re #189 (if this change feels ok to use, it might even close that issue!)
Thanks!
> Add exclude filter and reuse shared code between filters

- webapp/lib/model.g.dart
This PR contains no functional changes... just syntax style cleanup for new codegen
* switch to using [the new `typedef` declaration style](https://dart-lang.github.io/linter/lints/prefer_generic_function_type_aliases.html)
* use newer [function type parameter declaration style](https://dart-lang.github.io/linter/lints/use_function_type_syntax_for_parameters.html)
* mark overridden methods with `@override`
* whitespace cleanup
> codegen model style cleanup

- webapp/lib/model.g.dart
- webapp/lib/model.yaml
This updates `model.yaml` to use the [updated codegen new spec](https://docs.google.com/document/d/1Jnr6TRjZFIlyw_pVXIwB58aGmUxkcWWYasOVt_jL42E/edit#heading=h.k4tz0qvvaa32) with built-in and custom validation options. To accomplish this, existing `*.yaml` files must be updated so that codegen can distinguish default values from validation options.
Other changes include:
* changed `model.yaml` to specify `{}` as the default for `lastInboundTurnTagIds` to match earlier manual code modification
* minor updates to codegen add to and remove from set operations
> update model with new codegen

- tool/deploy_webapp.sh
This will help make Nook deployments faster by being able to specify that only hosting should be deployed (there's other options, but hosting will be most useful).
It will also make deployment to the SOM-CC project easier, as it has a different set of database access rules that we don't maintain in the repo, which have sometimes been accidentally overwritten on deployments.
Tested both with and without the flag in the latest round of Nook deployments.
> Add an optional --only flag to pass to firebase deploy

- webapp/lib/controller.dart
- webapp/lib/controller_view_helper.dart
- webapp/lib/view.dart
* Selected filter tags will be loaded from the URL on the first load of Nook, even with no conversation was selected. They will temporarily appear as their tag ID in yellow, and then will be replaced by their name once the tags have been loaded.
* Fixes handling of after date filters - they are now written and read from the URL properly
* Changes the conversation list panel to say "X/N conversations" - useful when filtering to know the total number of conversations
* Doesn't call `updateFilteredAndSelectedConversationLists` when no conversation list is selected, and filter tags and being adjusted (this was causing the "Select list" message to be cleared)
Note: this PR was developed on top of #427 , it will need to be merged after that one, and the target branch changed to master.
> Various tag filtering improvements

- .github/workflows/build_webapp.yml
`webdev 2.6` is the latest version of `webdev`, but it requires at least `build_web_compilers` version `2.12.0-dev.1`, which isn't production-ready yet, so `pub get` doesn't download it.
When `build_web_compilers 2.12.0` gets released, we can roll back this change.
> Use specific 2.5.9 version of webdev

- .github/workflows/build_webapp.yml
`webdev 2.6.1` was released a few days ago, and it removes the dependency on a dev version of `build_web_compilers`, so we no longer need to skip `2.6`
> Remove specific version for webdev

- webapp/lib/controller.dart
This was caused by the previous PR #417 that removed the shard-selection logic from view (which treated single-shard selectors differently to multi-shards), but then I didn't introduce it back in the controller.
> Fix single shard projects not loading any data

- webapp/lib/controller.dart
The last-inbound-turn tags are applied to the message not conversation - this PR loads them correctly from the message tags collection and refreshes the UI when the message tags have been downloaded from firebase
> Fix last inbound turn tag filter not loading correctly

- webapp/lib/lazy_list_view_model.dart
- webapp/lib/view.dart
Fixes https://github.com/larksystems/Katikati-Core/issues/218
Three main changes:
1. It turns out that calling `.clientHeight` on the individual elements is expensive as it triggers DOM reflow in order to compute it. Instead we can use the `scrollHeight` of the list container (with the scrollpad removed) to get the height of the current elements, and then approximately compute the number of elements to add to the view based on the average height of the existing ones. So less precise, but gives us better performance.
2. Add a method for removing a list of items, not just individual items.
3. Cache the UI elements rather than disposing them when they're removed from the UI when filtering. They will be disposed as expected when e.g. switching conversation lists.
Here is some performance …
> Performance improvements to conversation list filtering

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/controller_view_helper.dart
- webapp/lib/app/nook/view.dart
This allows better handling when the group of the tag changes, which currently fails with an "item not in list" error in view.dart on line 1150 as the previous group is lost, and the new group doesn't have that element.
> Handle tag modification as removal and addition

- webapp/lib/app/nook/view.dart
- webapp/web/converse/styles.css
The read/unread functionality isn't used at the moment since it doesn't work well when multiple people are using Nook and so it's currently disabled [from the engine](https://github.com/larksystems/katikati_lib.dart/blob/0890213290a35cdfe3e281917fed167b291ae9b7/lib/perspectives/export_to_firebase.dart#L146). This PR just clears up the UI for now, until we rethink how/if we should better design this and show it to users.
cc @elayabharath @lukechurch
> Remove mark unread button

- webapp/lib/app/configurator/standard_messages/controller.dart
- webapp/lib/app/configurator/standard_messages/view.dart
- webapp/lib/app/configurator/view.dart
- webapp/web/configure/buttons.css
- webapp/web/configure/configuration.css
- webapp/web/configure/modals.css
+ Made the design similar to the tags page
+ The collapse and expand works on the group level
+ Cleaned up layout to have standard padding, sizes
+ Save config floats over the messages when the form is dirty
+ When removing a message group, it expands to show all the messages that would be affected
> Messages refactor

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/controller_filter_helper.dart
- webapp/lib/app/nook/controller_view_helper.dart
- webapp/lib/platform/platform.dart
First step towards https://github.com/larksystems/Katikati-Core/issues/496
Next step will be to rename `[...]conversationTags` as just `[...]tags`
> Remove handling of separate message tags in Nook

- webapp/lib/app/configurator/standard_messages/controller.dart
- webapp/lib/app/configurator/tags/controller.dart
The view starts with a disabled save config button, and with the tags and messages sharing that code, but only being supported by the messages page, the tags config page was never enabling that button, and so you couldn't save.
Also:
* resets the bool keeping track of whether the form is dirty or not after a successful save
* marks form dirty when a message group is removed
> Enable save tag config button on changes

- .github/workflows/build_webapp.yml
The Github action fails because it pulls a dart 2.12 version
> Set the docker container version to use dart 2.10.4

- webapp/lib/app/configurator/tags/controller.dart
- webapp/lib/app/configurator/tags/controller_tag_helper.dart
- webapp/lib/app/configurator/tags/view.dart
Also includes a bug fix for the case where you would add a new group, rename it, then add a new tag - which would wrongly use the previous group name (the change for this is in `view.dart` only)
cc @lukechurch
> Move edited/deleted tag tracking in the tag manager

- .github/workflows/build_webapp.yml
- README.md
- webapp/pubspec.yaml
Several related changes:
* update the url in pubspec to use SSH rather than HTTPS
* update the Github CI to use the newer Dart Build and install an SSH key
* update the Github CI badge link in the README
If this looks good, I will pull together similar PRs for nook-configurator and katikati-reporting
cc @lukechurch
> update pubspec url

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/controller_view_helper.dart
- webapp/lib/app/nook/view.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
- webapp/web/converse/index.html
- webapp/web/converse/styles.css
The conversation list can now be sorted:
* alphabetically by conversation ID
* by the timestamp of the last incoming message
Also makes the sorting of the conversation list live - ie. it will be updated on each new incoming message
Closes https://github.com/larksystems/Katikati-Core/issues/524
Note to self: dependent on https://github.com/larksystems/katikati_common_lib/pull/52 so that one needs to be merged first and then the pubspec files here need to be updated with the merge SHA
> Add button for sorting the conversation list

- webapp/lib/app/configurator/tags/controller_tag_helper.dart
- webapp/lib/app/configurator/tags/controller_view_helper.dart
- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/controller_view_helper.dart
This removes references to the deprecated `Tag.group` field.
I've tested this to the best of my ability in an attempt to ensure no exceptions and no functional changes,
but please review with a critical eye.
> remove tag group references

- webapp/lib/platform/platform.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
This updates the call to the `Tag` listen method
and should land at the same time as https://github.com/larksystems/katikati_common_lib/pull/75.
> update tag listener method call

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/controller_filter_helper.dart
- webapp/lib/app/nook/controller_view_helper.dart
This fixes some issues with the mandatory filtering:
* live reaction to changes to the filters in Firebase and updates them as needed - fixes https://github.com/larksystems/Katikati-Core/issues/615
* correctly supports mandatory filtering in firebase becoming more permissive
It also adjusts mandatory filtering so that
* only tags added manually to the filter are highlighted on the conversation (likely fit to the use case of using filters to search for messages)
* only the manually added filters are added to the URL when the URL is updated (this is to ensure that when sharing URLs, only the manually added tags are carried over)
> Various improvements to mandatory filtering

- webapp/lib/app/configurator/standard_messages/controller.dart
- webapp/lib/app/configurator/tags/controller.dart
- webapp/lib/app/configurator/view.dart
+ Tested by editing the message, not saving, going to a different page (or refresh), alert pops up
+ Then clicked saved, navigate to different page, alert doesn't pop.
Closes https://github.com/larksystems/Katikati-Core/issues/631
> Ask for confirmation before the user leaves the configure pages

- webapp/lib/app/nook/controller.dart
+ `actionObjectState` is always `UIActionObject.loadingConversations` in this function, hence removed it from messages enabled as well. In any case, the enable / disable toggle should happen whenever the config changes irrespective of actionObjectState
Closes https://github.com/larksystems/Katikati-Core/issues/662
> Enable tag buttons on first load

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/view.dart
- webapp/web/converse/styles.css
+ Show instruction if no conversation tag or message is selected above the tags in the tag panel
+ Deselect a conversation when selecting message, and vice versa
closes https://github.com/larksystems/Katikati-Core/issues/622
> Select conversation summary to tag, not just active conversation

- webapp/lib/app/nook/controller_view_helper.dart
- webapp/lib/app/nook/lazy_list_view_model.dart
- webapp/lib/app/nook/view.dart
This fixes the previous logic which wasn't maintaining the sort order of the conversations correctly.
Also tries to reduce jitter in the conversation list when conversations update, but there is more that could be done on this.
And also fixes https://github.com/larksystems/Katikati-Core/issues/510 - this was caused by the lazy list class deciding whether to re-build an item based on `elementOrNull`, which wasn't being set (ie. was always `null`)
> Replace conversation list update with set from scratch

- webapp/lib/app/nook/controller.dart
TBR  fixes https://github.com/larksystems/Katikati-Core/issues/671
@lukechurch an explanation for the issue, which I didn't catch when reviewing your PR: `currentUserConfig` refers to the configuration for the user, which is empty if the user is to use the defaults for mandatory tag filters, while `currentConfig` represents the configuration to be applied to the UI (ie. the merger of `default` and `currentUserConfig`)
> Fix current config reference for the conversation filter

- webapp/lib/app/nook/controller.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
This fixes a problem when there are multiple messages pending in a conversation (with ID = `null`), and trying to select one of them, will throw a "bad state" error of "too many elements", as there are two messages with `null` as ID in the conversation
Needs https://github.com/larksystems/katikati_common_lib/pull/91
> Add pending ids to sent messages based on conversation

- webapp/lib/app/nook/dom_utils.dart
- webapp/lib/app/nook/view.dart
+ Instead of stop propagation on every interactive element, we have a generic function that determines if the shortcut is applicable or not. e.g. this handles "Enter" on a button, but when we author a button element we do not necessarily think of adding stopPropogation onKeyDown
+ Removed stopPropogations on makeEditable as they are not needed anymore
Closes https://github.com/larksystems/Katikati-Core/issues/670
> Ignore shortcuts on interactive html elements

- webapp/lib/app/nook/controller.dart
- webapp/lib/app/nook/view.dart
Noticed a bug where the conversation summary doesn't show any of the pending or failed statuses
> Reflect conversation summary status in the conversation from changes in the conversation from firebase

- webapp/lib/app/nook/view.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
- webapp/web/converse/styles.css
Fixes https://github.com/larksystems/Katikati-Core/issues/692
The problem was that the conversation item is now wrapped in a classless div, and the other user presence indicator requires its parent to be relative so it can position itself floating on top, relative to top/bottom.
Also moves it to the bottom so it doesn't appear on top of the datetime
> Fix user presence indicator not being on the conversation item

- webapp/lib/app/nook/view.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
bringing in https://github.com/larksystems/katikati_common_lib/pull/103 to fix enter on inline tag creation moving to the next conversation (and changing the `makeEditable` to react on `onKeyUp`, which is more consistent with desired behaviour
TBR
> fix enter misbehaving on inline tag creation

- webapp/lib/app/nook/view.dart
We don't need to draw attention to old failed messages, so just use the last message instead
TBR
> Show only the status of the last message in the conversation list

- webapp/lib/app/nook/controller_view_helper.dart
- webapp/lib/app/nook/view.dart
Maintain all datetime data in utc, but convert it to local only at the time of display
Fixed a wrong type declaration `{dateTime: DateTime}` - not sure how the compiler hasn't complained about this
Closes https://github.com/larksystems/Katikati-Core/issues/712
> Show messages time adjusted for local timezone

- webapp/lib/app/configurator/standard_messages/controller.dart
- webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
- webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
- webapp/lib/app/configurator/standard_messages/view.dart
- webapp/lib/app/configurator/tags/controller_tag_helper.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
Main DS changes
`MessageCategory` under `controller_messages_helper.dart` now takes in categoryName
`categories` under `StandardMessagesManager` is not a simple map of <String(categoryName), String(groupName), ...SuggestedReplies> but`<String(categoryId), MessageCategory>` hence we would be using categories[categoryId]._groups_[groupId]._messages_[messageId] / constructing this new data type for update/render methods
- Renamed `id` to be of messageId / groupId / categoryId where applicable for easier comprehension
- Changed all the maps to use Id instead of Name for both category / group
- Removed 2 unused methods related to `sequenceNumber`
> Refactor messages configuration page to use (category/groupId) instead of (category/group)Name

- webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
Sometimes when the category/group index is missing (those saved from a different branch), the user cannot add new category/group
> Fix the crash where index are missing when adding new category/group

- webapp/lib/app/nook/controller.dart
This causes the number of selected in conversations list to be wrong (possibly one of the reasons)
Potentially fixes https://github.com/larksystems/Katikati-Core/issues/851
> Null check for conversations with empty messages

- webapp/lib/app/configurator/standard_messages/controller.dart
- webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
+ Do not show reset button as soon as a message is added for the first time
+ Correct for lastIndex of messages, groups, categories that are greater than the parent length
+ Fix the case where the messages in storage might be null hindering comparison i.e. when a new message/group/category is just added
Related https://github.com/larksystems/Katikati-Core/issues/881
> Fix for bugs in standard messages page

- webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
In cases where categories/groups/messages get added and then deleted, the greatest index is greater than than the length of the list. Capping the new index at the length of the list results in the order of the elements being weird.
We will have a sparse index, so the index field is not as much of an index as it is an ordering-field, but I think that's fine. Can you check that it doesn't get in the way of the re-ordering (and in fact, may well be helped by it)?
TBR @elayabharath
> Allow the index to be greater than length

- webapp/lib/app/configurator/tags/view.dart
- webapp/web/configure/tags.css
- webapp/web/configure/tags.html
I think this slipped through a while back when we added the tooltip to some of the accordion buttons
TBR
> Rename tooltip class for sample messages and import tooltip.css

- webapp/lib/app/configurator/tags/controller.dart
- webapp/lib/app/configurator/tags/controller_tag_helper.dart
- webapp/lib/app/configurator/tags/controller_view_helper.dart
- webapp/lib/app/configurator/tags/view.dart
- webapp/pubspec.lock
- webapp/pubspec.yaml
+ New tag manager to include local, storage data, simplified APIs
+ View & view helpers uses group id as the identifier instead of group name
+ Promise await store methods for more reliable save indicator
Known bugs:
+ newly created tag not updating on save, duplicates
+ group's unsaved indicator not cleared
+ _removeTagsFromView should not be called on already deleted group
+ group name can be duplicate, need to build checks
+ Storage vs local diffs are yet to be added
+ Error checks on the TagManager methods
> Config tag refactor to include local & storage

- webapp/lib/app/users/app.dart
- webapp/lib/app/users/controller.dart
- webapp/lib/app/users/view.dart
- webapp/lib/platform/platform.dart
- webapp/web/users/index.html
- webapp/web/users/main.dart
- webapp/web/users/users.css
Access via /users/index.html
+ User permissions are displayed in a table (toggles are checkboxes, text & tags are text boxes)
+ Reads from, saves directly to fire store
+ Handles display of values derived from default, along with reset to default
+ Unsaved indicator in the email header
+ Sticky headers, first column. Hover indicators for easier comprehension. Visual grouping for permissions
Limitations
1. Tags input is not smart, for not requires list of comma separated tag ids
2. Conflicts are not handled
3. Toggle all on/off is not available
4. Removed email does not reflect
> User permissions page
