webapp/lib/controller.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart

This adds the capability for displaying admin-level messages across all clients via a new `systemMessages` collection in firebase... but does not actually display those messages yet.

system messages

---

webapp/lib/controller.dart
webapp/lib/view.dart
webapp/web/index.html
webapp/web/snackbar.css

Hi @lukechurch and @danrubel 
As discussed, this adds a notification via a snackbar at the bottom of the screen similar to the one from Coda. Let me know if you have any feedback on the design - happy to make any adjustments etc.
Screenshot:
Thanks!

Add snackbar notification UI

---

tool/Pipfile
tool/Pipfile.lock
tool/clear_firebase.py
tool/firebase_root_keys.py
tool/firebase_to_json.py
tool/json_to_firebase.py
tool/migrate_firebase.py
tool/migrate_json.py
tool/migrate_nook_model.py
tool/validate_firebase.py
tool/validate_nook_model.py
tool/validate_nook_model_custom.py

No changes... just moving common tools out of individual projects into nook
Feel free to land this after reviewing if all looks good.

move common tools into nook project

---

webapp/lib/view.dart
webapp/web/banner.css
webapp/web/index.html

Add a simple notification banner

---

webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart

Small cleanup of platform / model code.
Feel free to land this if the review looks good.

move collection name into model

---

tool/migrate_firebase.py
tool/migrate_nook_model.py
tool/validate_firebase.py
tool/validate_nook_model.py

This updates the migration and validation scripts to
* validate the MessageStatus if it is defined (we should require it at some point)
* validate SuggestedReply documents
* migrate MessageStatus if it is invalid
Feel free to land this if the review looks good.

migrate/validate MessageStatus/SuggestedReply

---

tool/validate_firebase.py
tool/validate_nook_model.py

Minor update to validation scripts to validate SystemMessage docs.
Also reorders `validate_SuggestedReply_doc` (no code change) to match codegen.
Feel free to land this if the review looks good.

validate system message

---

tool/firebase_root_keys.py

Feel free to land this if the changes look good

fix firebase root keys to include uuid-table

---

webapp/lib/model.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart

Two cleanups and one fix:
* move Conversation.collectionName into model
* remove datetime default
* fix batch update unread flag

model cleanup

---

webapp/lib/controller.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart

See https://github.com/larksystems/KK-Project-2020-IOM/issues/18

redirect Conversation.notes to be updated via pub/sub

---

webapp/lib/controller.dart

TBR https://github.com/larksystems/nook/pull/198 that was approved but not landed properly.

cleanup save note action

---

webapp/lib/view.dart

This updates areas that are editable so that text editing keystrokes in that area do not also trigger messages to be sent or tags to be applied.

prevent text edit keystrokes from triggering actions

---

functions/package-lock.json
functions/package.json

This upgrades the firebase function dependencies for Publish and Log scripts. I've deployed the functions to nook-experimental and all appears to work.

update firebase function dependencies

---

webapp/lib/controller.dart

This refactors `SaveNoteAction` into a more generic `SaveTextAction` class which can be used in subsequent PRs.

Refactor save text action

---

webapp/lib/view.dart
webapp/web/tags.css

Fix long tags overflowing parent box

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart

Fix error when UI loads with no conversations

---

webapp/web/snackbar.css

This increases the width of the snackbar to better display error messages.

increase snackbar width

---

webapp/lib/controller.dart
webapp/lib/model.dart

This addresses comments in https://github.com/larksystems/nook/pull/221

address comments

---

tool/add_to_firebase.py
tool/tests/test_suggested_replies.json
tool/tests/test_tags.json

This is a bit hacky but works for now.
@lukechurch I've also added a couple of test/sample files for how the input should look like. Let me know if it looks ok, or if you'd prefer a different format.
Thanks!

Add script to upload replies and tags to firebase

---

webapp/lib/view.dart
webapp/web/styles.css

Add the short nook id in the conversation summary

---

webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

Demo screenshot:
@lukechurch if you'd like to hide other types of tags, plmk
Thanks!

Add a toggle in the tags panel for hiding age tags

---

webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

Merge reviewed PRs from dev branch into master

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

This adds a panel at the bottom of the conversation where a one-off message can be written. The user will be asked to confirm before sending the message.
Screenshots of the flow:

Add support for sending a one-off reply

---

webapp/lib/view.dart

@lukechurch 
This should fix the issue you're seeing with all messages dated as today, sorry for the mistake!

Use and format message time not DateTime.now()

---

webapp/lib/controller.dart
webapp/lib/view.dart

On hover, each suggestion will look as follows:

Add second button to send translation as well as main reply text

---

tool/add_to_firebase.py
tool/tests/test_suggested_replies.json
webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/model.g.dart
webapp/lib/platform.dart
webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

The master head has been deployed from, so I'm creating a checkpoint for it in the production branch.
cc @lukechurch , @danrubel

Updating production branch with master

---

webapp/lib/controller_view_helper.dart

As discussed in #243 in comments.
Thanks!

Fallback to sorting by shortcut if sequence numbers are null

---

tool/add_to_firebase.py
webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/model.g.dart
webapp/lib/view.dart

A demo screenshot, with some test categories:
@danrubel feel free to review this even if it's been merged, as we may need to merge it before you get the chance to have a look at it.
Thanks!

Group suggested replies via a category field

---

webapp/web/styles.css

* Make the tag filter menu wider
* Add an invisible element to the left of the menu to capture mouse hovering, making the menu less eager to disappear
Thank you!

A couple usability improvements for the tag filtering menu

---

tool/compute_tag_analytics.py

This currently relies on a hard-coded list of tags as I didn't want to spam the output with e.g. age tags. If you'd prefer a different approach, plmk.
Thanks!

Add a script to compute some tag analytics

---

deployment/deploy.sh

Store the latest git commit hash on deployment

---

webapp/lib/controller.dart
webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

Increase the density of replies in Nook

Css updates

---

webapp/lib/controller.dart

This will need undoing during generalisation #266

Filter age -> Filter demogs

---

tool/compute_tag_analytics.py

[Note for merging: relies on #261 to be merged first, and then the destination branch of this PR will need changing to master]

Add reporting for total messages/conversations

---

tool/compute_tag_analytics.py

I accidentally didn't update the base branch when merging #264, so I'm opening this PR to merge it into master.
No review needed, code has been reviewed in #264

Add reporting for total messages/conversations -> merging into master

---

tool/compute_tag_analytics.py

[Note for merging: relies on #261 to be merged first, and then the destination branch of this PR will need changing to master]

Add needs reply analytics

---

webapp/lib/controller.dart
webapp/lib/view.dart

Hide demog tags by default

---

webapp/web/styles.css

Allow conversation tags to wrap on multiple lines

---

tool/compute_tag_analytics.py
webapp/lib/controller.dart
webapp/lib/view.dart
webapp/web/styles.css

Update production branch with latest on master to prepare for a new release & deployment

Merge master into production branch

---

tool/compute_tag_analytics.py

@marianamarasoiu because of a problem with Nook production fixes this needs an urgent TBR merge. Apologies.
Please let me know if you need changes afterwards

Updates to needs reply metrics

---

webapp/lib/view.dart
webapp/web/styles.css

This adds the UI elements for https://github.com/larksystems/nook/issues/263 but no functionality hooked up yet.
Feel free to squash/merge this PR if it looks good.
----------------

display dropdown of conversation lists

---

webapp/lib/controller.dart
webapp/lib/platform.dart
webapp/lib/view.dart
webapp/web/actions.css
webapp/web/styles.css

Re #286 - only 3/4, toggling tag panel visibility is lower priority and requires a bit more CSS work than just marking it as hidden, will follow up in a next PR.
@lukechurch At the moment, these get set when the user first loads Nook and don't get updated during the session (as I didn't expect they would need to), but if they should get updated throughout, plmk and I'll add that in.
Thank you!

Makes several UI features customizable (turn on / off) via a firebase users table

---

tool/system_metrics_monitor.py

Provide help information on arguments needed to run script.

---

tool/Pipfile
tool/Pipfile.lock
tool/firebase_to_json.py
tool/json_to_firebase.py
tool/tool_utils.py

This is an example of what integrating the new logger will look like, fairly minimal changes as you can see. I'll roll this out across the rest of the tools if you're happy

Integrate New Logger

---

tool/add_to_firebase.py
tool/clear_firebase.py

Apologies for the silly diff - I foolishly adjusted the indent to do the conversion to `__main__` at the same time.
The actual changes are pretty minimal, it basically adds audit and notify calls.

Update logging implementation for clear and add

---

tool/firebase_root_keys.py

A change for if/when we move to sharded conversations.
Feel free to merge this when the time is right.

update firebase root keys for json download

---

tool/Pipfile
tool/Pipfile.lock

I could not get the tools working after sync to HEAD... This fixed it.

update nook tool pipfile

---

tool/json_to_firebase.py

Push subcollections to firestore individually

---

webapp/lib/model.g.dart
webapp/lib/model.yaml

I think this is the only changes that need making to propagate Ids into the model? Will need other changes before it's ready to actually be used etc.

Add ids to messages

---

webapp/lib/controller.dart

This was introduced in #321 but got overwritten by #325

Bring back sending multi-manual messages & confirmation

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/pubsub.dart
webapp/lib/view.dart
webapp/web/messages.css

If send reply or send multi reply fails, then 
* a snackbar is displayed indicating the failure
* the message text is displayed with red strike-through
Also, publish logging has been enhanced to better collate http responses

message status and logging improvements

---

webapp/lib/controller.dart
webapp/lib/platform.dart

This refactors `sendReply` and `sendMultiReply` to use a new `onError` parameter to handle send message exceptions.

refactor send reply to have onError param

---

functions/index.js

This adds a status reporting function - at the moment it's a clone of the log function, but they fairly logically separate so given different names. Once this has landed I'll point an uptime monitoring tool at the statusZ endpoint

Add StatusZ

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/logger.dart
webapp/lib/platform.dart
webapp/lib/platform_constants.dart
webapp/lib/pubsub.dart
webapp/lib/view.dart

Reviewed in #333 
cc @danrubel @lukechurch

Merge uptime monitoring into master

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml

And also consolidate the filtering in the _populateTagView methods.
Temporarily consider the field optional - will make it required and remove the null check once the infrastructure is updated to push the field to firebase.

Add a filterable field to tags to reduce the filter list

---

webapp/lib/model.dart
webapp/lib/model.g.dart

This cleans up model code formatting in preparation for `add_opinion` codegen.
* remove unused MessageCollectionListener
* cleanup formatting
* no functional changes

cleanup model

---

webapp/lib/controller.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart

Per comments in https://github.com/larksystems/nook/pull/374, this functionality is not used now and is not intended to be used in the future.

remove unused functionality

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/styles.css
webapp/web/utilities.css

This removes the need to keep track in the controller of which group is being shown currently.
Re #349

Rewrite the group tags UI to show all tags in foldable menus

---

tool/deploy_webapp.sh

Add optional arg to deploy script to skip deploying cloud functions

---

webapp/lib/view.dart

Make filter tag lists folded by default

---

webapp/lib/controller.dart
webapp/lib/view.dart

The UI (and implementation approach) is very similar to what we do for suggested replies.
Closes #385

Group tags in RHS panel and show groups in dropdown selector

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart

Update the active conversation in place

---

webapp/lib/model.g.dart

This adds validation methods to the model to be used in the future with the new codegen.
No functional changes.

codegen validation methods

---

tool/build_model.sh

Move the build model script from `Infrastructure/tool` to this project

move and simplify build model script

---

webapp/lib/controller.dart
webapp/lib/view.dart
webapp/web/messages.css

- Switch to onblur to decrease fighting during text update (patch fix)
- Decrease the wait time after activation
- Use pending status to guide display

New pending behaviour + updates liveness

---

webapp/lib/view.dart

I think this will fix the self-race conditions we're currently experiencing

Swith onInput -> onBlur

---

webapp/lib/controller.dart

The conversation loader stopped appearing sometime during the last few PRs because it was getting overridden by a call to `updateFilteredAndSelectedConversationLists`. This adds it back by tracking when it should be shown.

Add a loading state to know when to show the loader

---

webapp/lib/controller.dart
webapp/lib/view.dart

First part for being able to select a conversation via URL ( #316 )

Add shard ID to page URL

---

webapp/lib/controller.dart
webapp/lib/model.dart
webapp/lib/view.dart

Final step for being able to point to a conversation via the URL. Fixes #316

Add conversation ID to the URL

---

webapp/lib/controller.dart
webapp/lib/controller_filter_helper.dart
webapp/lib/view.dart
webapp/web/styles.css

Screenshots:
It works with both short and long IDs.
Note: this PR was developed on top of #426 , it will need to be merged after that one, and the target branch changed to master.

Add a filter component to search by conversation ID

---

webapp/lib/controller.dart
webapp/lib/model.g.dart
webapp/lib/platform.dart

No dataset access UI

---

webapp/lib/view.dart

When adding a new tag, scroll it into view if needed

---

tool/add_to_firebase.py
webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/model.dart
webapp/lib/model.g.dart
webapp/lib/model.yaml
webapp/lib/platform.dart
webapp/lib/view.dart
webapp/web/actions.css

Deployed to [nook-dev](https://nook-development.firebaseapp.com/?) for testing.
Next step is to add `send_messages_to_ids` action to the pubsub handler, and then transition Nook to only using that one instead of `send_to_multi_ids`.

Add multiple reply message packs

---

tool/adhoc/migrate_conversation_metrics_model.py

Add script to migrate conversation metrics model

---

webapp/lib/platform.dart

towards https://github.com/larksystems/Katikati-Core/issues/365

Remove deprecated send_to_multi_ids

---

tool/deploy_webapp.sh

TBR - identical chance as reviewed in https://github.com/larksystems/nook/pull/450

Copy nook configurator in before deployment

---

webapp/lib/controller.dart
webapp/lib/user_position_reporter.dart

@marianamarasoiu - this adds a simple transitory user presence system for reporting which conversation a user had opened.

Report user presence

---

tool/deploy_webapp.sh

Fixes https://github.com/larksystems/Katikati-Core/issues/403

Add validation for the cloud function URLs

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/styles.css

A very hacky fix to show only the messages that are part of the cohort conversation. This PR only merges into the separate branch for the EiE project, and not into the main branch.

Show only cohort-only messages

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/tags.css

Note: This PR only merges into the separate branch for the EiE project, and not into the main branch.

Highlight the tags that are used in the filter on the message

---

webapp/lib/controller.dart
webapp/lib/controller_view_helper.dart
webapp/lib/view.dart
webapp/web/tags.css

TBR
The code was reviewed in https://github.com/larksystems/nook/pull/455 - this PR is just bringing that PR from a project prod branch into master

Highlight the filtering tags on the message

---

webapp/lib/controller.dart
webapp/lib/controller_platform_helper.dart
webapp/lib/platform.dart
webapp/lib/view.dart
webapp/pubspec.yaml
webapp/web/messages.css
webapp/web/tags.css

I think this gets it mostly there, will follow up with a final polish on how it feels to use.

First pass towards being able to add new inline tags

---

webapp/lib/view.dart
webapp/web/tags.css

* enter accepts the new proposed tag - closes https://github.com/larksystems/Katikati-Core/issues/385
* colour the accept/reject buttons - closes https://github.com/larksystems/Katikati-Core/issues/386
* the icon-like buttons to add/remove/accept are now thicker - closes https://github.com/larksystems/Katikati-Core/issues/387

A few improvements to inline editing

---

webapp/lib/controller.dart
webapp/lib/controller_platform_helper.dart
webapp/lib/platform.dart
webapp/lib/view.dart
webapp/pubspec.yaml
webapp/web/messages.css
webapp/web/tags.css

TBR
This is just bringing into master code that was developed and reviewed in a project prod branch (https://github.com/larksystems/nook/pull/456 and https://github.com/larksystems/nook/pull/458)

Inline tag creation

---

webapp/lib/controller.dart
webapp/lib/view.dart

+ Removed the url parameter to disable replies feature
+ Set the config `replies_panel_visibility` to false for a specific account in firebase to see if the suggested panels is hidden

Remove disable replies feature from the URL parameter

---

tool/build_model.sh
webapp/lib/model/model.yaml

+ Update model path
+ Made sure there is no diff in model.g.dart (except the commented out log at L315) against the script at https://github.com/larksystems/Infrastructure/pull/43

Move User presence to be generated by modelgen

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

+ Hides / shows entire panel only when either notes / replies panel is enabled
+ Clears the panel title before appending

Selective toggle for replies / notes panel

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_filter_helper.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.yaml

⚠️ Merge after updating the ref from katikati_ui_lib

Use URL view from katikati_ui_lib

---

webapp/lib/app/nook/view.dart

I think this fix slipped by in the repo restructuring from a few weeks ago, so adding it now

Fix local variable declaration shadowing class attribute

---

webapp/lib/app/configurator/tags/view.dart

Closes https://github.com/larksystems/Katikati-Core/issues/449

Replace × with "Close" for the sample messages tooltip

---

webapp/lib/app/configurator/standard_messages/view.dart
webapp/web/configure/configuration.css

Closes https://github.com/larksystems/Katikati-Core/issues/450

Configure messages page: Moved delete button from the left to the right side

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart

The button is no longer needed since tags can now be grouped
cc @elayabharath @lukechurch

Remove button to hide demog tags

---

webapp/lib/app/configurator/tags/view.dart
webapp/lib/app/configurator/view.dart

Fix folding and rename behaviour of tag groups

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/view.dart
webapp/lib/app/configurator/view.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.yaml
webapp/web/configure/buttons.css
webapp/web/configure/configuration.css
webapp/web/configure/modals.css

+ Verified that the back page link is before the conversation selector, and the user presence is aligned to the right

Integrate back page style from katikati_ui_lib

---

webapp/lib/controller.dart
webapp/lib/view.dart
webapp/pubspec.yaml

This updates Nook to use https://github.com/larksystems/katikati_ui_lib.dart/pull/23

Update Nook to new auth info

---

webapp/lib/view.dart
webapp/pubspec.yaml

New branding logic

---

webapp/lib/app/nook/view.dart
webapp/lib/view.dart
webapp/web/converse/styles.css

+ Independently scrollable panels, with the existing functionality
+ Selected messages styling
+ Display none for hiding the after date filter since it was adding a few pixels at the bottom
+ Updated a inline divs to spans
+ Pending on the selective toggle for the tags panel - this seems like a lot to take on in this PR, hence will push as separate PR

Layout for nook

---

webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_filter_helper.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/platform/platform.dart

towards https://github.com/larksystems/Katikati-Core/issues/496

Rename *conversationTags* to *tags*

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/lib/platform/platform.dart
webapp/pubspec.yaml
webapp/web/converse/index.html
webapp/web/converse/tags.css

Relies on https://github.com/larksystems/katikati_ui_lib.dart/pull/33, which will need to be merged first
cc @lukechurch

Support handling of suggested tags

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/lib/platform/platform.dart
webapp/pubspec.yaml
webapp/web/converse/actions.css
webapp/web/converse/index.html
webapp/web/converse/messages.css
webapp/web/converse/styles.css
webapp/web/converse/tags.css

This is still a prototype and in need of a bit more testing. Long term, we should be using the components that are being developed in kk_ui_lib, but for now, this just adjusts the existing UI elements slightly to accommodate a suggested messages panel below the message text box.
Relies on https://github.com/larksystems/katikati_ui_lib.dart/pull/34, which will need to be merged first, and the pubspec ref updated here.
cc @lukechurch

Add suggested messages in a conversation

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/configurator/standard_messages/view.dart
webapp/lib/platform/platform.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/configuration.css
webapp/web/configure/messages.html

Pending:
1. Rename of the group name not working

Integrate accordion, editable text for messages config page

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

TBR
close https://github.com/larksystems/Katikati-Core/issues/525
cc @elayabharath

Bold conversations with "our turn" label & show the last message of the conversation

---

webapp/lib/app/homepage/view.dart

Enable link to explorer in dashboard by default

---

webapp/pubspec.lock
webapp/pubspec.yaml

Update pipfile to pull in turnline prototype

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/converse/index.html
webapp/web/converse/styles.css

TBR cc @elayabharath @lukechurch

Integrate turnline

---

webapp/lib/app/nook/controller_view_helper.dart

Turnline fix to actually add the views to the UI

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

Remove add tags/messages actions

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart

TBR @elayabharath 
closes https://github.com/larksystems/Katikati-Core/issues/562

Maintain message selected and tag inline focus when conversation updates

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/configurator/standard_messages/view.dart
webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/configurator/tags/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/messages.css
webapp/web/configure/messages.html

TBR @elayabharath 
closes https://github.com/larksystems/Katikati-Core/issues/447

Foldable standard messages to support adding new categories

---

webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart

Use ID random generator to avoid ID seq clash

---

webapp/lib/app/configurator/standard_messages/view.dart

Fixes https://github.com/larksystems/Katikati-Core/issues/620
TBR @elayabharath

Show placeholder for message translations in config page

---

tool/deploy_webapp.sh

Small adjustments to the deploy script

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

References https://github.com/larksystems/Katikati-Core/issues/526

Show date separators in conversation messages list

---

webapp/lib/app/nook/controller_view_helper.dart

Closes https://github.com/larksystems/Katikati-Core/issues/512

Show group indicator, title for 1 message group under standard messages

---

webapp/lib/controller.dart

Remove default exclude tag as it's not a tag valid across projects

---

webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Needs to be merged after pubspec has been updated with https://github.com/larksystems/katikati_common_lib/pull/84

Support conversations with no messages

---

webapp/lib/app/configurator/view.dart
webapp/web/configure/configuration.css

Closes https://github.com/larksystems/Katikati-Core/issues/533

Prominent orange save button on the top right of the config page

---

webapp/lib/app/configurator/tags/view.dart

+ When the user leaves the tag, we start a timer for 100ms and by the end of it, if the user is mouse over on the tooltip, we make it stay. Not sure if this is a good strategy, but without embedding this tooltip inside the tag - I can't make the tooltip stay using the mouse enter / leave.
Closes https://github.com/larksystems/Katikati-Core/issues/632

Fix the sample messages tooltip disappearing when mouse leaving on tag

---

webapp/lib/app/configurator/tags/sample_data_helper.dart
webapp/lib/app/configurator/tags/view.dart
webapp/web/configure/tags.css

+ Added a default loading state, placeholder text when no messages are present
+ Added a link icon to the text message
Closes https://github.com/larksystems/Katikati-Core/issues/452

Link messages to respective conversation

---

webapp/lib/app/nook/view.dart

Closes https://github.com/larksystems/Katikati-Core/issues/623

Clicking on tag on tag panel tags the message / conversation

---

webapp/lib/app/nook/view.dart
webapp/web/converse/actions.css

Hide "Send" against empty message
Hide "Send all" button if any of the messages are empty
Placeholder for empty text / translation
Closes https://github.com/larksystems/Katikati-Core/issues/621

Hide buttons for empty standard messages

---

webapp/lib/app/nook/view.dart
webapp/web/converse/messages.css

Also adds a tag for failed messages
Related to https://github.com/larksystems/Katikati-Core/issues/661

Show pending tag on pending message

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

Related to https://github.com/larksystems/Katikati-Core/issues/598

Config for turnline, default tab

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

Closes https://github.com/larksystems/Katikati-Core/issues/614

Make mandatory tags non removable under conversation filters

---

webapp/lib/app/configurator/tags/controller_view_helper.dart
webapp/pubspec.lock
webapp/pubspec.yaml

- Adding a new group, selects the title text by default so user can start typing
- The group is expanded so the user can start adding tags
Warning: Do not merge without  https://github.com/larksystems/katikati_common_lib/pull/85
Closes: https://github.com/larksystems/Katikati-Core/issues/575

Add tag UX improvements

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

Just a change based on the new project logics - TBR

Change conversation unread logic based on needs reply tag

---

webapp/lib/app/nook/controller.dart

Fixes https://github.com/larksystems/Katikati-Core/issues/638

Scroll to the last message in the conversation on load

---

webapp/web/configure/messages.html
webapp/web/configure/tags.html
webapp/web/converse/index.html
webapp/web/index.html

Merge after https://github.com/larksystems/katikati_common_lib/pull/98

Integrate favicon

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

Closes https://github.com/larksystems/Katikati-Core/issues/666

Improvements to new incoming messages for active conversation

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

Closes https://github.com/larksystems/Katikati-Core/issues/672

Disable buttons if no message or conversation summary is selected

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart

Closes https://github.com/larksystems/Katikati-Core/issues/661

Reflect status in conversation list when user sends messages

---

webapp/lib/app/nook/view.dart

Merge after https://github.com/larksystems/katikati_common_lib/pull/95

Fix conversation width overflow issue

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/lazy_list_view_model.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

To be merged along with https://github.com/larksystems/katikati_common_lib/pull/92
Closes https://github.com/larksystems/Katikati-Core/issues/526

Render date separator for conversation list

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/converse/messages.css

... and right align the tags and swap the tag actions
merge after https://github.com/larksystems/katikati_common_lib/pull/96

Bring the tags for outgoing messages to the left

---

webapp/lib/app/configurator/tags/view.dart

+ Added "cache" for the messages to prevent fetching them multiple times. Please let me know if this is not desirable (since rest of the app is realtime)
Closes https://github.com/larksystems/Katikati-Core/issues/668

Disable deletion of tags if it is used across any message

---

webapp/lib/app/nook/controller_view_helper.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Expand next step in the turnline

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart

Harden turnline-related code and re-disable turnline by default

---

webapp/lib/app/nook/lazy_list_view_model.dart
webapp/lib/app/nook/view.dart

Fix number of filtered conversations out of total

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/configurator/tags/controller_view_helper.dart

+ On adding a category or a message group, we expand the accordion and focus the title to edit
+ minor: changed the double negation under tag view helper
Closes https://github.com/larksystems/Katikati-Core/issues/691

Enhancements when adding standard messages under configure page

---

webapp/pubspec.lock
webapp/pubspec.yaml

Update pubspec with message sort order fixed

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart

Use reply id instead of index

---

.gitignore
webapp/lib/app/nook/view.dart
webapp/lib/controller.dart
webapp/lib/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Depends on https://github.com/larksystems/katikati_common_lib/pull/109
the project configuration file looks like:
```
{
"projectTitle": "New Project 2021",
"loginTitle": "New Project 2021",
"domainsInfo": {
"Katikati": "katikati.world",
"New Project": "new-project.com"
},
"firstLanguage": "en",
"secondLanguage": "-"
}
```

Add project specific configuration read from file

---

webapp/lib/controller.dart
webapp/lib/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Fix auth info not showing by updating pubspec

---

webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/configurator/tags/controller_view_helper.dart
webapp/lib/app/configurator/tags/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Merge after https://github.com/larksystems/katikati_common_lib/pull/117

Show warning when creating duplicate tags

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/converse/index.html

Merge after https://github.com/larksystems/katikati_common_lib/pull/116

Integrate new tag with autocomplete suggestions

---

webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Merge after https://github.com/larksystems/katikati_common_lib/pull/123

Loading spinner for conversations

---

webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/configurator/tags/controller_tag_helper.dart
webapp/lib/app/configurator/tags/controller_view_helper.dart
webapp/lib/app/configurator/tags/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/tags.css
webapp/web/configure/tags.html

The design implemented slightly deviates from the figma file since
1. there are a lot of hover behaviour in one place
2. menu position on top right make the tag visually cluttered
Merge after https://github.com/larksystems/katikati_common_lib/pull/122

Added mark as important, copy tag id using menus for config page

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/converse/styles.css

Merge after https://github.com/larksystems/katikati_common_lib/pull/121
https://github.com/larksystems/Katikati-Core/issues/723

Replace tag dropdown with accordion in the tag panel

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/actions.css

Closes https://github.com/larksystems/Katikati-Core/issues/481
TBR @elayabharath

De-empahsize standard messages that have already been sent

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart

Add configuration for sendable message groups

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

https://github.com/larksystems/Katikati-Core/issues/747
+ Remove 'Enter' shortcut

Handle previous / next conversation from conversation summary, shortcuts

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/dom_utils.dart
webapp/lib/app/nook/view.dart

Closes https://github.com/larksystems/Katikati-Core/issues/746

Bulk select / deselect conversations using shift key

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/dom_utils.dart
webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

Closes https://github.com/larksystems/Katikati-Core/issues/745

Show selected count in the conversation list panel

---

webapp/lib/app/nook/controller.dart
webapp/lib/platform/platform.dart

Closes https://github.com/larksystems/Katikati-Core/issues/665

Moved the 1 message / 1 message group to reuse multi functions

---

webapp/lib/app/configurator/tags/view.dart
webapp/web/configure/tags.css

Closes https://github.com/larksystems/Katikati-Core/issues/405

Scroll the page when trying to drag a tag beyond the vertical limits

---

firestore.rules

towards https://github.com/larksystems/Katikati-Core/issues/715

Update firestore.rules for a multi-tenancy setup

---

webapp/pubspec.lock
webapp/pubspec.yaml

Update pubspec with latest ui lib

---

webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/pubspec.lock
webapp/pubspec.yaml

https://github.com/larksystems/Katikati-Core/pull/810

Update for model

---

webapp/lib/app/homepage/controller.dart
webapp/lib/app/homepage/view.dart

Add link to Coda from the homepage

---

webapp/lib/platform/platform.dart

send client version to server during heartbeat

heartbeat send version

---

webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/pubspec.lock
webapp/pubspec.yaml

TBR @elayabharath 
I needed to update nook to use the latest kk_common_lib, so this might cause some merge conflicts for you at some point..

Update pubspec & rename groupDescription -> groupName

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/lib/controller.dart

Extract snackbar command to the main controller

---

webapp/lib/app/nook/controller.dart
webapp/lib/platform/platform.dart

closes https://github.com/larksystems/Katikati-Core/issues/837

When signing out from conversations page, firebase subscriptions need to be cancelled, shards reset on login

---

webapp/lib/view.dart
webapp/web/configure/messages.html
webapp/web/configure/tags.html
webapp/web/converse/index.html
webapp/web/index.html

Closes https://github.com/larksystems/Katikati-Core/issues/797

Show project title in the tabs

---

webapp/web/converse/styles.css

Max height + scroll
Closes https://github.com/larksystems/Katikati-Core/issues/805

Handle a lot of tags in the filter conversation UI

---

webapp/lib/app/configurator/tags/view.dart
webapp/lib/app/developer/app.dart
webapp/lib/app/developer/controller.dart
webapp/lib/app/developer/utils.dart
webapp/lib/app/developer/view.dart
webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/developer/developer.css
webapp/web/developer/index.html
webapp/web/developer/main.dart

+ Empty toggle button that sets the state in localStorage

Show developer mode

---

webapp/lib/app/nook/controller.dart

closes https://github.com/larksystems/Katikati-Core/issues/842

Populate last inbound turn tags filter menu

---

webapp/lib/platform/platform.dart

switch conversationTags to tags firebase collection

listen for tags

---

cloud_functions/requirements.txt

Add itsdangeous lib to fix cf deploy issue

---

webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/configurator/tags/view.dart
webapp/lib/app/nook/controller.dart
webapp/pubspec.lock
webapp/pubspec.yaml

NOTE: before merging, the pubspec needs to be updated to use https://github.com/larksystems/katikati_common_lib/pull/138

Add more user configs

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/web/configure/messages.css

+ Subtler indicator instead of a warning sign
+ Remove unnecessary warning during the transition state

Flush save indicators per message

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/configurator/standard_messages/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/configuration.css
webapp/web/configure/messages.css
webapp/web/configure/messages.html

Changes from the previous commit are still persisting for some reason, will remove it in the following commits

Reset for renames of groups, categories, edits of messages, translation

---

webapp/lib/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Merging since we spoke in the call regarding this @marianamarasoiu

Update katikati common lib

---

webapp/lib/app/nook/controller.dart

Partially fixes https://github.com/larksystems/Katikati-Core/issues/847

Fix the standard messages jump when a new message pops up in the active conversation

---

webapp/web/configure/messages.html
webapp/web/converse/styles.css

Closes
https://github.com/larksystems/Katikati-Core/issues/888
https://github.com/larksystems/Katikati-Core/issues/889

Scroll bar issues

---

webapp/lib/app/configurator/standard_messages/view.dart

Related https://github.com/larksystems/Katikati-Core/issues/881

Prevent self checks on category name, group name

---

webapp/lib/app/configurator/standard_messages/controller_view_helper.dart

TBR @elayabharath 
(also remove a sort-by-index which doesn't have any effect)

Fix & use group index in category not category Index

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/standard_messages/controller_messages_helper.dart
webapp/lib/app/configurator/standard_messages/controller_view_helper.dart
webapp/lib/app/configurator/standard_messages/view.dart

Needs https://github.com/larksystems/katikati_common_lib/pull/148

Reorder message categories, groups

---

webapp/lib/app/configurator/standard_messages/controller.dart
webapp/lib/app/configurator/tags/controller.dart
webapp/lib/app/developer/controller.dart
webapp/lib/app/homepage/controller.dart
webapp/lib/app/homepage/view.dart
webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/lib/controller.dart
webapp/lib/platform/platform.dart
webapp/lib/platform/user_position_reporter.dart
webapp/lib/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Move project configuration to firebase

---

webapp/lib/app/configurator/tags/controller_tag_helper.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Fix add tag in converse and group del in configurator

---

webapp/pubspec.lock
webapp/pubspec.yaml

Update pubspec to fix accordion issue

---

README.md

TBR
Closes https://github.com/larksystems/Katikati-Core/issues/477

Populate readme

---

cloud_functions/main.py

Support oauth token for use with Google AppsScript

---

webapp/lib/app/nook/view.dart
webapp/web/converse/styles.css

Indicate start of conversation if there aren't any messages

---

webapp/lib/app/users/controller.dart
webapp/lib/app/users/view.dart
webapp/web/users/users.css

* Add project selector to navbar
* Adjust table scrolling
* Make highlight of row/column less striking
* Animate row and column on save
* and others..

Various improvements to user config page

---

webapp/lib/app/users/controller.dart
webapp/lib/app/users/view.dart
webapp/lib/platform/platform.dart
webapp/web/users/index.html
webapp/web/users/users.css

Various user config page improvements

---

webapp/lib/app/configurator/project/controller.dart
webapp/lib/app/configurator/project/view.dart
webapp/lib/controller.dart
webapp/lib/platform/platform.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/project.css
webapp/web/configure/project.html

Add project config fields

---

webapp/pubspec.lock
webapp/pubspec.yaml

Update pubspec with project map field fix

---

webapp/lib/platform/platform.dart

Add getter for pubsub instance

---

webapp/lib/app/homepage/controller.dart
webapp/lib/controller.dart

Add link to admin pages

---

webapp/lib/app/configurator/project/controller.dart
webapp/lib/app/configurator/project/view.dart
webapp/web/configure/project.css

Improve logic for handling modifications & deactivated users

---

webapp/lib/app/configurator/tags/view.dart

Fix message/tag link not containing a reference to the project & conversation list

---

webapp/lib/app/configurator/tags/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Move conversation view link generator to common lib

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/lib/platform/platform.dart
webapp/pubspec.lock
webapp/pubspec.yaml
webapp/web/configure/messages.html
webapp/web/configure/project.html
webapp/web/configure/tags.html
webapp/web/converse/index.html
webapp/web/dashboard.html
webapp/web/developer/index.html
webapp/web/index.html

Show telegram images if a message is an image filename

---

webapp/lib/app/configurator/project/view.dart
webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/platform/platform.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Support for deanonymised conversations

---

webapp/lib/app/nook/controller_filter_helper.dart
webapp/lib/app/nook/view.dart

Support filtering by number if available

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Add ability to edit std message before sending

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/view.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Correctly set the max freetext message length

---

webapp/lib/app/nook/controller.dart
webapp/lib/app/nook/controller_view_helper.dart
webapp/lib/platform/platform.dart
webapp/lib/utils.dart
webapp/pubspec.lock
webapp/pubspec.yaml

Query conversations based on include tags

---

webapp/lib/app/nook/controller.dart

Get total conversations number from metrics
